### ISSUE TITLE
Update Java Version

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#4204]
## Description

Due to security reasons as well as questions of support it is necessary to update the Java Version.
As Java 11 is a Version with Long time Support, it is recommended to use it for further development.
As a sideeffect, the Tomcat version needs to be updated to be compatible.
Furthermore all dependencies needs to be checked for new versions to keep them compatible.

## TODO:
- [ ] Make source code Java 11 compatible
- [ ] change Java version in required places (e.g. pom)
- [ ] check dependencies for newer versions and update them
- [ ] update tomcat to Version 9
- [ ] replace or remove tomcat-maven-plugin

## Estimated Costs and Complexity
This is a **mid-range** project for about 7-9 PT

## Related Issues
* #4106 
* #2929

**Comment by solth** [comment]
>     * update tomcat to Version 8

Since we already verified in several installations that the most current version of Kitodo.Production 3.x runs on Tomcat 9 I would suggest to update to that version instead.

**Comment by stefanCCS** [comment]
Good idea, lets do it!
