### ISSUE TITLE
Provide Application Metrics though the Prometheus Format

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#4314]
## Description
Kitodo currently has no standardized way to provide metrics about the application to external Monitoring and Alerting Systems. By adding Prometheus support to Kitodo, the application would be easy to integrate into a variety of Observability Platforms. This would allow for greater insight into the state of the application.

Prometheus provides a J ava Client with support for which makes exposing metrics fairly straight forward.

## To-do

- [ ]	Review the feasibility of integrating Prometheus to Kitodo Production
- [ ]	List possible metrics to expose
- [ ]	Update the Build System
- [ ]	Implement the exposure of metrics into Kitodo Production
- [ ]	Update Documentation
- [ ]	(Optional) Create an official Grafana Dashboard for Kitodo Production

**Comment by stweil** [comment]
Should this issue be tagged for the development fund 2023?
