### ISSUE TITLE
Add Support for S3 compatible Object Storage

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#4316]
## Description
Kitodo currently relies on the File System to store production Data. This limits the flexibility and scalability of Kitodo Production installations. Especially in a Cloud Environment. The goal of this proposal is to remove the dependency of the application on the (local) File System. By providing native S3 Support, Kitodo Production could utilize a variety of Object Storage Systems (minio,
 wasabi) and by extension enable the operation of Kitodo Production in a more distributed fashion allowing for greater horizontal scaling.

## To-do

- [ ]	Review the feasibility of native Object Storage Support for Kitodo Production.
- [ ]	Create a Concept for how Kitodo Production would manage Data without relying on a File System and utilizing an S3 compatible Object Store instead.
- [ ]	Implement the proposed Concept
- [ ]	Update the Documentation

**Comment by matthias-ronge** [comment]
@Kathrin-Huber, is this more like a bring-back of the broken “swap to tape drive” function (aka. swapfolder) of Production 2, or more like doing the file management in a separate component, as I recently suggested in issue #4327? (If the latter, I would close my ticket as duplicate.)

**Comment by stweil** [comment]
Should this issue be closed? Or be tagged for development fund 2023?
