### ISSUE TITLE
[ZM] Erscheinungsverlauf-Reimport 

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#53]
#### Beantwortung zu Rückfragen:

Die Parameter-Datei […] muss geeignet sein, den Zustand des Formulares vollständig wieder herzustellen (über ein Einlesen zu Beginn)
#### Grobkonzept:

Im kalendarischen Editor kann […] eine zuvor mit diesem ausgespeicherte Parameterdatei wieder eingelesen werden.
#### Lösungsvorschlag:

Im Dialog „Erscheinungsverlauf“ kann eine XML-Datei, die mit Goobi exportiert wurde wieder geladen werden. Der Dialog wird auf den in dieser Datei gegebenen Stand gesetzt.
#### Setzt voraus:
- [ ] #41 [ZM] Neuer DocType “Zeitung”
- [ ] #43 [ZM] Regelsatzkonfiguration
- [ ] #45 [ZM] Erscheinungsverlauf-Editor
- [ ] #50 [ZM] Aggregierungsdialog
- [ ] #51 [ZM] Erscheinungsverlauf-Export
