### ISSUE TITLE
[ZM] Batches nach logistischen Kriterien

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#54]
#### Leistungsbeschreibung:

Das […] Anlegen von Vorgängen muss derart ermöglicht werden, dass im Workflow gut handhabbare Segmente entstehen, um die Logistik des Aushebens, des Transports und der Verarbeitung im eigenen oder fremden Digitalisierungsdienstleistungsbereich optimal gestalten zu können.
#### Grobkonzept:

Um trotzdem gut handhabbare Segmente für die Logistik des Aushebens, des Transports und der Verarbeitung zu  erhalten, wird Goobi um eine Möglichkeit zum Anlegen von Vorgängen nach logistischen Kriterien erweitert. Neben der Aufteilung des gesamten Erscheinungsverlaufes einer Zeitung in einzelne Vorgänge in Goobi, soll bei der Anlage der Vorgänge die Möglichkeit gegeben werden, Gruppen von Vorgängen dem Goobi-Modul „Batches“ zuzuordnen. Diese sollten durch den Bearbeiter in sinnvoller Weise an logistischen oder physischen Einheiten orientiert werden. Die Einheiten werden, wenn eine einfache Systematik gegeben ist (z.B. „Kalendermonate“), automatisch erzeugt, aber auch manuell zugeordnet werden können.
#### Lösungsvorschlag:

Neben der Aufteilung des gesamten Erscheinungsverlaufes einer Zeitung in einzelne Vorgänge in Goobi soll bei der Anlage der Vorgänge die Möglichkeit geschaffen werden, Gruppen von Vorgängen dem Goobi-Modul „Batches“ zuzuordnen. Diese sollten durch den Bearbeiter sinnvollerweise an logistischen oder physischen Einheiten orientiert werden. Die Einheiten sollen, wenn ein entsprechendes System gegeben ist (z.B. „Kalendermonate“) automatisch erzeugt, aber auch manuell zugeordnet werden können.
#### Setzt voraus:
- [ ] #41 [ZM] Neuer DocType “Zeitung”
- [ ] #43 [ZM] Regelsatzkonfiguration
- [ ] #45 [ZM] Erscheinungsverlauf-Editor
- [ ] #50 [ZM] Aggregierungsdialog
- [ ] #52 [ZM] Anlegen von Vorgängen
