### ISSUE TITLE
[ZM] Aggregation von Jahrgängen

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#56]
#### Leistungsbeschreibung:

Unabhängig von der gewählten Aggregierung der Ausgaben muss zusätzlich ein Segment auf Jahresebene gebildet werden, um mit dem DFG-Viewer konform zu sein.
#### Grobkonzept:

Es wird eine Möglichkeit zur automatischen Aggregation von Jahrgängen entwickelt, die ein Batch automatisch nach einem Auswahlkriterium, etwa einer Jahreszahl in einem bestimmten Feld, erstellt, etwa um diesen dann mit einer gemeinsamen Ankerdatei zu exportieren.
#### Lösungsvorschlag:

Es soll eine Möglichkeit geschaffen werden, dass ein Batch automatisch nach einem Auswahlkriterium (z.B. des Zeitungstitels, ggf. und-verknüpft mit einem bestimmten Jahr) in einem bestimmten Feld, erstellt wird. Dazu wird der Dialog „Batches“ um ein Suchfeld erweitert. Mit der Suche wird ein Batch zusammengestellt.
#### Bemerkungen:

Es werden für den DFG-Viewer drei Ebenen benötigt: Zeitung (gesamt), Jahr und Tag. Es ist bekannt, dass, wenn bei „Tag“ auf die unterste Ebene verlinkt wird und diese mehrere Ausgaben beinhaltet, dies zur Folge hat, dass immer auf das erste Image der untersten Ebene gesprungen wird, in vielen Fällen also auf den falschen Tag. Es wäre schön, wenn dieses Problem zukünftig beispielsweise durch die OAI-Schnittstelle gelöst werden könnte.
#### Setzt voraus:
- [x] #41 [ZM] Neuer DocType “Zeitung”
- [x] #43 [ZM] Regelsatzkonfiguration
- [x] #45 [ZM] Erscheinungsverlauf-Editor
- [x] #50 [ZM] Aggregierungsdialog
- [x] #52 [ZM] Anlegen von Vorgängen
