### ISSUE TITLE
[ZM] Anreicherung von Metadaten

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#57]
#### Leistungsbeschreibung:

Die […] Metadaten müssen […] auf Ausgabenebene […] angereichert werden können.
#### Lösungsvorschlag:

Anreicherung beschreibt den Vorgang, Datensätze automatisch zu selektieren und um weitere Daten zu ergänzen. In Fällen, in denen mehrere Ausgaben in einem Goobi-Vorgang gemeinsam verwaltet werden, kann dies wünschenswert sein, um nicht viele Strukturelemente von Hand öffnen und eine Angabe ergänzen zu müssen. Beispielsweise wird nach einer Ansetzungsform gesucht und eine Verweisform angereichert.Es soll eine Möglichkeit geschaffen werden, Strukturelemente systematisch auszuwählen und automatisch um ein bestimmtes Metadatum ergänzen zu können.
#### Setzt voraus:
- [ ] #41 [ZM] Neuer DocType “Zeitung”
- [ ] #43 [ZM] Regelsatzkonfiguration
- [ ] #45 [ZM] Erscheinungsverlauf-Editor
- [ ] #50 [ZM] Aggregierungsdialog
- [ ] #52 [ZM] Anlegen von Vorgängen
