### ISSUE TITLE
[ZM] Laden einer OVU-PPN-Liste

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#58]
#### Leistungsbeschreibung:

Hierzu müssen auf der Basis von Parameterdateien, die die Ausgabenstruktur einer Zeitung beschreiben […] zunächst geeignete Vorgänge angelegt werden.
#### Beantwortung zu Rückfragen:

In der zweiten Stufe wird eine Liste der PPNs der benötigten Ovu-Sätze eingelesen und auf dieser Grundlage entsprechende Goobi-Vorgänge angelegt.
[…]
Eine Suche nach den PPNs der Ovu-Sätze im PICA CBS soll nicht erfolgen. […] die […] PPNs werden in einer Liste abgelegt, die wiederum auf der nächsten Bearbeitungsstufe von Goobi eingelesen wird, um entsprechende Vorgänge zu erzeugen.
#### Grobkonzept:

In Goobi wird eine Möglichkeit zum Erzeugen von Vorgängen auf Basis von Parameterdateien geschaffen werden. Im kalendarischen Editor kann zu diesem Zweck eine […] Parameterdatei […] eingelesen werden.
[…]
Eine Möglichkeit zum Anlegen von Vorgängen nach PPNs vervollständigt das Modul Vorgangserzeugung: Anhand einer Liste der benötigten PPNs werden vollautomatisch Goobi-Vorgänge angelegt.
#### Lösungsvorschlag:

Es ist noch nicht ganz klar, was ein OVU-Satz ist. Vermutlich enthält er bereits Angaben zu einem Digitalisat, d.h. die Granualarität. Es soll möglich sein, in den kalendarischen Editor interaktiv eine Datei mit einer Liste von PPNs von OVU-Sätzen einzufügen, mit welche Goobi vollautomatisch Vorgänge angelegt.
#### Setzt voraus:
- [ ] #41 [ZM] Neuer DocType “Zeitung”
- [ ] #43 [ZM] Regelsatzkonfiguration
- [ ] #45 [ZM] Erscheinungsverlauf-Editor
- [ ] #50 [ZM] Aggregierungsdialog
- [ ] #52 [ZM] Anlegen von Vorgängen
- [ ] #55 [ZM] CBS-Import mit Ovu-Sätzen
