### ISSUE TITLE
[ZM] Generieren von Supraankern

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#59]
#### Leistungsbeschreibung:

[…] und später zu einem Gesamterscheinungszeitraum kombiniert und exportiert werden. […]
- Es muss sichergestellt werden, dass nachtägliches Hinzufügen / Löschen von einzelnen Vorgängen in der Gesamtstruktur des Erscheinungsverlaufs der Zeitung […] auch entsprechend korrekt in der Gesamtstruktur wiedergegeben werden.
##### Erweiterung Anchor-Konzept:

Um bei z.B. mehrbändigen Werken die Beziehung zur Überaufnahme herzustellen zu können und damit der Bände untereinander, werden sogenannte Anchor-Dateien (METS) genutzt. In diesen befinden sich nur die Metadaten der Überaufnahme ohne Strukturen und Dateigruppen. Es wird dann aus der METS-Datei des Bandes selbst (was einem Vorgang in Goobi entspricht) auf diese verwiesen.
Da Goobi keinerlei Beziehung zwischen verschiedenen Vorgängen bezüglich der Metadaten kennt, wird diese Beziehung erst in der Präsentation hergestellt. Dies ist möglich, da die Anchor-Dateien für jeden Band identisch sind (insb. der Identifier). Der Nachteil hierbei ist, dass Änderungen an den Metadaten der Überaufnahme in allen zugehörigen Vorgängen einzeln nachgeführt werden müssen. Dies führt im Kontext der Zeitungsdigitalisierung zu einem erheblichen Mehraufwand bei notwendigen Anpassungen und ist auch bei der Bearbeitung herkömmlicher Medien häufig problematisch. Um zentrale Anchor-Dateien nutzen zu können, ist Goobi so zu erweitern, dass die Metadaten der Anchor-Datei an einer Stelle bearbeitet werden können. Die Anchor-Dateien enthalten dann auch Verweise zu allen über- und untergeordneten Hierarchiestufen. Dabei können die Daten, wie bisher, nur von einem berechtigten Benutzer zur selben Zeit bearbeitet werden.

Weiterhin wird eine Möglichkeit zum nachträglichen Zusammenfassung von Vor-gängen zu Erscheinungszeiträumen entwickelt, so dass für in einem Batch zusammengefasste Vorgänge eine gemeinsame Ankerdatei generiert wird und die Vorgänge auf einmal, jeweils mit der neuen Ankerdatei, exportiert werden können.
[…]

Beilagen sind nach Punkt 2.2 „Beantwortung zu Rückfragen zur Goobi.production Ausschreibung“ abbildbar.

Goobi und die genutzte UGH-Bibliothek werden so erweitert, dass das neue Anchor-Konzept genutzt werden kann.
[…]
Das erweiterte Anchor-Konzept erlaubt auch das Vererben auf Ausgabenebene, da bei Bearbeitung einer übergeordneten Einheit alle untergeordneten Einheiten (z.B. Ausgabe) bekannt sind.
#### Lösungsvorschlag:

Für in einem (Jahrgangs- oder Gesamtausgabe-) Batch zusammengefasste Vorgänge soll eine gemeinsame Ankerdatei generiert und diese zu den Vorgängen ergänzt werden. Dabei müssen die Metadaten aus den einzelnen Vorgängen eines Batches gesammelt und in die Ankerdatei (nach oben) vererbt werden. Die Ankerdatei wird bei jedem Vorgang abgelegt.
#### Setzt voraus:
- [ ] #41 [ZM] Neuer DocType “Zeitung”
- [ ] #43 [ZM] Regelsatzkonfiguration
- [ ] #45 [ZM] Erscheinungsverlauf-Editor
- [ ] #50 [ZM] Aggregierungsdialog
- [ ] #52 [ZM] Anlegen von Vorgängen
- [ ] #56 [ZM] Aggregation von Jahrgängen
