### ISSUE TITLE
Toughen Kitodo.Production up to handle RDA meta-data

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#619]
**Approach:** RDA meta-data shall be treated as meta-data groups. Using meta-data groups is already possible. PICA data can be imported, and they can be exported to METS&lt;MODS>-XML. However, in some records the RDA meta-data is not—or not to its whole—contained in the title record, just an identifier PPN is given which has to be retrieved separately from the catalogue. Exporting to METS&lt;MODS> cannot yet write attributes which is required for the GND identifier.

**Requirements:**

- [x] Toughen the UGH library up to export fields of meta-data groups to MODS XML attributes
- [x] Port norm data import to work with meta-data groups
- [x] Toughen the PICA plug-in up to resolve norm data records included by their PPN only

The development of this feature is funded by Staatsbibliothek zu Berlin − Preußischer Kulturbesitz.

**Comment by henning-gerhardt** [comment]
Is this feature for Kitodo.Production 2.x or 3.x (DFG based development)?

**Comment by matthias-ronge** [comment]
2.x − developed in behalf of Staatsbibliothek zu Berlin − Preußischer Kulturbesitz

**Comment by henning-gerhardt** [comment]
Thank you. I added general Kitodo.Production 2.x milestone and change this milestone after merged pull request or before next 2.x release.
